# Generated by Django 4.1.7 on 2023-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings_unit",
            field=models.CharField(default="vazio", max_length=65),
            preserve_default=False,
        ),
    ]
