# Generated by Django 4.1.7 on 2023-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_servings_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
